### ISSUE TITLE
Mass outage detection

### ISSUE THREAD

**Issue by auxesis** [flapjack/flapjack#19]
When a service event’s status is a failure, for each tag associated with the check and entity, update a counter. 

This can be used by filters later on to suppress + collapse notifications if the counter exceeds a threshold.

**Comment by jessereynolds** [comment]
We could narrow down the tags this applies to, eg by a configurable regex eg matching one of:

```
^datacentre:
^region:
^availability_zone:
^storage:
```

**Comment by ali-graham** [comment]
Closing this in favour of #833.

**Comment by jessereynolds** [comment]
Thumbs up
