### ISSUE TITLE
API: harmonisation of time input/output

### ISSUE THREAD

**Issue by ali-graham** [flapjack/flapjack#219]
All time parameters accepted in the API should be accepted as either a number (directly via JSON), a string composed only of digits (\d+), or as an [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601)-formatted string. The last will be converted to the server's timezone while the others will be assumed to have been pre-converted to it before conversion to the epoch timestamp.

At the moment it's taking iso8601 strings as time input but emitting seconds since the epoch as time output. We could allow an option to emit times as iso8601 as well, but that's probably less useful.

**Comment by jessereynolds** [comment]
> All time parameters accepted in the API should be accepted as either a number (directly via JSON), a string composed only of digits (\d+), or as an ISO 8601-formatted string. The last will be converted to the server's timezone while the others will be assumed to have been pre-converted to it before conversion to the epoch timestamp.

Actually, ISO 8601 strings optionally include timezone information, either 'Z' for UTC or as an offset from UTC. We should take the timezone info from the string, not assume the time of the server. Also, I'd argue we should reject ISO 8601 strings that do not specify timezone information as ambiguous.

**Comment by ali-graham** [comment]
(When I say "converted to the server's timezone" I mean taking the included timezone into account, rather than overwriting it -- and this is only for calculations where all elements must be in the same timezone to make sense.)

**Comment by jessereynolds** [comment]
@ali-graham gotcha, oops.

**Comment by ali-graham** [comment]
The code in `master` now enforces this better, due to the consistent data interfaces, so I'll mark this closed.
