### ISSUE TITLE
The "Alerting Checks" shows checks that do not fall under the notification rules

### ISSUE THREAD

**Issue by jswoods** [flapjack/flapjack#421]
The "Alerting Checks" under the contact page does filter out the ack'd/maintenance states, but it does not apply the notification rules filter. So you end up seeing checks in this table for which you were never notified.

**Comment by ali-graham** [comment]
Work has just been merged which should fix this in master, I'll try to check tomorrow.

**Comment by ali-graham** [comment]
Verified fixed in master, after various fixes to resolve bugs introduced by the recent changes which made this stuff work. :smile:
