### ISSUE TITLE
Rollup alerts include checks that do not fall under the notification rules

### ISSUE THREAD

**Issue by jswoods** [flapjack/flapjack#422]
I have a contact who is only suppose to get disk notifications, so I have removed all media from the default notification rule and created a new rule on the "check_disk" tag. When the original alerts occur, I am correctly notified of only the disk events; however, when the rollup/reminder notifications occur they include checks that do not include the check_disk tag.

Here's what the reminder event looks like:

Problem summary: Critical: 6 (Critical: soa-test-svc1-1.phx1.jivehosted.com:check_event-persistence-deployable_default, soa-test-svc1-1.phx1.jivehosted.com:check_rebuild-job-deployable_default, soa-test-svc1-1.phx1.jivehosted.com:check_view-persistence-deployable_default, jcint-test-ssd4.phx1.jivehosted.com:check_disk, jcint-test-ssd2.phx1.jivehosted.com:check_disk, jcint-test-ssd3.phx1.jivehosted.com:check_disk)

And interestingly, those checks correspond to the checks that show up under the "Alerting Checks" section of the contact page:
![screenshot 2014-01-21 09 56 44](https://f.cloud.github.com/assets/1730965/1966227/77334c2c-82c5-11e3-8e49-4ba8bd4c8ffb.png)

For that reason, I believe that functionally this is related to https://github.com/flpjck/flapjack/issues/421.

**Comment by ali-graham** [comment]
Verified fixed in master, after various fixes to resolve bugs introduced by the recent changes which made this stuff work. :smile:
