### ISSUE TITLE
Allow renaming of entities and checks

### ISSUE THREAD

**Issue by ali-graham** [flapjack/flapjack#445]
Due to certain decisions early on in the development of Flapjack, entity and check names are acting as core identifiers for their respective data records. In working on the JSONAPI gateway, some conflicts between accepted best practice and the way we currently do things have arisen.

So far, @jessereynolds and I have established a few principles for future development on this, but it would be too large a change for the imminent Flapjack 1.0 release.

* accepting ids from external sources in the API POSTs is not a good idea; we may need to support a 'userdata' hash for entities and contacts, which could store one or more external referent(s) for those records. All ids should be generated by Flapjack on record creation.

* renaming of entities is not currently possible; a different name is considered a different entity. A switch to 'id'-based referencing would allow this.

* notification rules are bound to entities by name, and they should instead store the id of the named entity as at creation/update time.

Some of this is currently handled in the Flapjack 2.0 candidate branch https://github.com/ali-graham/flapjack/tree/threading_and_sandstorm, largely through the use of ActiveModel.

We should probably document the consequences of the current implementation as well.

**Comment by ali-graham** [comment]
Renaming of checks should work OK in master currently, so moving to the 2.0 milestone and will check shortly.

**Comment by jessereynolds** [comment]
> Renaming of checks should work OK in master currently, so moving to the 2.0 milestone and will check shortly.

@ali-graham - how's this looking now?

**Comment by ali-graham** [comment]
Comfortable to close as implemented -- names are just another property of a check in master, nothing's internally dependent on them remaining the same.
