### ISSUE TITLE
Pagerduty gateway - when polling for acks, get all acks at once

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#452]
Pagerduty's incidents api allows for retrieving all unresolved incidents in one go:

http://developer.pagerduty.com/documentation/rest/incidents/list

Eg:

`https://acme.pagerduty.com/api/v1/incidents?fields=incident_number,status`

In addition to adding a webhooks receiver for state changes from pagerduty (see #391), we should improve the polling interface to make just one request per contact/subdomain. We will likely need to support both polling and webhooks as some sites will prefer one over the other, or will want to employ both (for best of both worlds).

**Comment by ali-graham** [comment]
I'm not sure what the bounty rules are regarding the release of the code -- this has been fixed in `master`, but v2 (which is what `master` is aiming towards) is still a little while away from a release.

**Comment by chrisgagne** [comment]
@ali-graham A major project maintainer has accepted the fix into master. That's good enough for me. :) I'll approve the claim from @kbailey4444.
