### ISSUE TITLE
Tag events with times, dates

### ISSUE THREAD

**Issue by auxesis** [flapjack/flapjack#509]
This would allow people to create notification rules that match only events that occur on particular dates and times of day. 

Thoughts on the tags we should automatically generate:

```
time:%H:%M:%S 
time:%H:%M
time:%H
date:%Y-%m-%d
date:%Y-%m
weekday:%A (full weekday name)
weekday:%a (abbreviated weekday name)
month:%B (full month name)
month:%b (abbreviated month name)
dayofweek:%u 
weekofyear:%W
```

(Makes me a little reminiscent of the [Sandbox WordPress theme](https://code.google.com/p/sandbox-theme/wiki/ExampleCSS_indexPHP) which would dynamically generate classes on content based on the datetime information on the post)

/cc @portertech @calebhailey

**Comment by jessereynolds** [comment]
It seems this isn't actively desired by anyone at the moment, and the primary functionality is delivered already via `time_restrictions`, so closing.
