### ISSUE TITLE
Write developer documentation

### ISSUE THREAD

**Issue by auxesis** [flapjack/flapjack#51]
Should at a minimum cover: 

 - Coding standards
 - Running tests
 - Contribution process
 - Releasing
 - (placeholder text saying “read the architecture documentation first”)
 - Redis database instances
 - Redis data structures
 - Writing gateways
 - Writing pikelets
 - Importing contacts and entities (talking to the API)
 - How to benchmark

For the moment, we should: 

 * Put all the above documentation into a single document (e.g. `DEVELOPING.markdown`) in the [Flapjack GitHub Wiki](https://github.com/flpjck/flapjack.wiki.git). 
 * Make README.markdown a quickstart guide, with appropriate pointers to `DEVELOPING.markdown`

Make `doc/ ` a git submodule of the Flapjack GitHub Wiki.

**Comment by Hobbsee** [comment]
Moved to https://github.com/flapjack/flapjack.io/issues/16.
