### ISSUE TITLE
Events with zero-length summary rejected

### ISSUE THREAD

**Issue by blalor** [flapjack/flapjack#513]
If I put an event like this into Redis:
```
{
    "entity": "web-lb-gen-001.us-east-1.aws.prd.myco.com",
    "check": "serfHealth",
    "type": "service", 
    "state": "ok", 
    "summary": "",
    "details": "",
    "time": 1400171748
}
```

I get this error, and the event is dropped:
```
2014-05-15T16:36:29+00:00 [ERROR] :: flapjack-processor :: Invalid event data received, Event hash has missing keys 'summary' {"entity"=>"web-lb-gen-001.us-east-1.aws.prd.myco.com", "check"=>"serfHealth", "type"=>"service", "state"=>"ok", "summary"=>"", "details"=>"", "time"=>1400171748}
```

The `summary` key *does* exist, but it's an empty string.

**Comment by paulhamby** [comment]
I agree that the summary key should be optional. Is there any compelling reason that it should remain required.

Would a PR be acceptable?

**Comment by jessereynolds** [comment]
Having summary optional makes sense to me.

**Comment by ali-graham** [comment]
I'm working on this now (`master` first, `maint/1.x` after that); the various output templates need their usage of the summary hedged, so it's not just the event model that changes.
