### ISSUE TITLE
Special chars in scheduled maintenance need converting to HTML encodings

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#561]
Eg, the following scheduled maintenance string (as retrieved from redis via redis-cli) causes the check detail screen to 500:

```
UAT \xe2\x80\x93 Environment is turned off most of the time.
```
(The first char seems to be this char: â, i'm not sure what the others are.)

The error thrown in the browser:

```
ArgumentError at /check
invalid byte sequence in US-ASCII
file: erb.rb location: gsub line: 912
```

that line:

```ruby
      s.to_s.gsub(/&/, "&amp;").gsub(/\"/, "&quot;").gsub(/>/, "&gt;").gsub(/</, "&lt;")
```

**Comment by Hobbsee** [comment]
Relates to #801, #802

**Comment by Hobbsee** [comment]
@ali-graham has confirmed that #805 fixes this.
