### ISSUE TITLE
mute all notifications matching a regex (via web, api, jabber)

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#61]
eg via jabber:

 flapjack: mute /foo-app-0[123]/ duration: 30 minutes

Possible implementation:
- create a key 'mute_regexs' that is a list of regular expressions
- create an event filter that looks to see if the entity_check key (ie the "$entity:$check" string for the service event) matches any of the regexs, if it does, block

The mute_regexs can be manipulated via web interface, api interface, and jabber gateway. 

Note, not sure how to implement the auto expiry of each mute regex. Perhaps each one should be in a separate string key with expiry, and provide pointers to these from a sorted set ...

**Comment by Hobbsee** [comment]
Isn't this just scheduling maintenance?

**Comment by ali-graham** [comment]
:+1:
