### ISSUE TITLE
Flapjack gives no indication it failed to start correctly

### ISSUE THREAD

**Issue by SarahKowalik** [flapjack/flapjack#616]
flapjack ➤ flapjack server start 
Flapjack starting...Daemon has started successfully
 done.
flapjack ➤ flapjack server status 
error: Flapjack is not running
/Users/sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app.rb:224:in `exit_now!': Flapjack is not running (GLI::CustomExit)
	from /Users/sarah/src/flpjck/flapjack/lib/flapjack/cli/server.rb:117:in `status'
	from /Users/sarah/src/flpjck/flapjack/lib/flapjack/cli/server.rb:256:in `block (3 levels) in <top (required)>'
	from /Users/sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
	from /Users/sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
	from /Users/sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /Users/sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
	from /Users/sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
	from /Users/sarah/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
	from bin/flapjack:53:in `<main>'

**Comment by ali-graham** [comment]
Closing this as daemonisation code has been removed in master; if this is instead against 1.x, please indicate and re-open.
