### ISSUE TITLE
web ui: Handle empty entity ID better

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#622]
Instigate autogeneration of an entity ID if it is an empty string

Otherwise you get entity pages looking like:

![screen shot 2014-08-22 at 12 13 53 am](https://cloud.githubusercontent.com/assets/391439/3997207/6c7e1310-293d-11e4-8c5a-525c25d60e02.png)

**Comment by Hobbsee** [comment]
This was done in a previous release.
