### ISSUE TITLE
Performance improvements for self_stats

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#681]
Split out the more intensive operations (eg I think the check freshness distribution) to separate pages, and separate metrics json endpoints, so it's much lighter to view the basic info. Similarly for self_stats.json (and probably move these to the jsonapi).

**Comment by jessereynolds** [comment]
@ali-graham for the self_stats.json are you OK with the idea of splitting this up into separate API endpoints for each subset of metrics? And moving to the api?

**Comment by ali-graham** [comment]
There is already https://github.com/flapjack/flapjack/blob/maint/1.x/lib/flapjack/gateways/jsonapi/metrics_methods.rb , I think those are the same; if not a few more might be needed. A separate endpoint per method will be required as well.

**Comment by ali-graham** [comment]
:+1: to the split, of course; performance work in the maintenance branch is painful, one of the main reasons for the data rework in master, so anything we can do to minimise expensive operations is preferred.

**Comment by jessereynolds** [comment]
How about these new GET endpoints to jsonapi: 

## /metrics/check_freshness
```json
check_freshness: {
0: 0,
60: 0,
300: 0,
900: 0,
3600: 9
}
```

## /metrics/entities_summary
```json
entities: {
all: 10,
enabled: 7,
failing: 3
}
```

## /metrics/checks_summary
```json
checks: {
all: 9,
failing: 3
}
```

## /metrics/event_queue
```json
event_queue: {
  length: 0
}
```

## /metrics/processed_events_summary
```json
processed_events_summary: {
all: 153,
failure: 104,
ok: 12,
invalid: 29,
action: 8
}
```

**Comment by jessereynolds** [comment]
Perhaps "_summary" in some of these is redundant and should be removed.

**Comment by ali-graham** [comment]
:+1: to removing _summary , and the new endpoints in general. I'll see what I can do in master to have an actual data model backing this as well.

**Comment by jessereynolds** [comment]
Great, thanks @ali-graham
