### ISSUE TITLE
Trusty / Precise apt sources wrong way round on website

### ISSUE THREAD

**Issue by nielsgoossens** [flapjack/flapjack#755]
On http://flapjack.io/docs/1.0/usage/Installation/, where it describes installation on Debian, Ubuntu, the line reads:
'# Ubuntu Trusty
echo 'deb http://packages.flapjack.io/deb precise main' | sudo tee  /etc/apt/sources.list.d/flapjack.list
'# Ubuntu Precise
echo 'deb http://packages.flapjack.io/deb trusty main' | sudo tee  /etc/apt/sources.list.d/flapjack.list

This should be:
'# Ubuntu Precise
echo 'deb http://packages.flapjack.io/deb precise main' | sudo tee  /etc/apt/sources.list.d/flapjack.list
'# Ubuntu Trusty
echo 'deb http://packages.flapjack.io/deb trusty main' | sudo tee  /etc/apt/sources.list.d/flapjack.list

**Comment by ali-graham** [comment]
Moved to the above issue on the website repo.

**Comment by nielsgoossens** [comment]
actually on further inspection there are no trusty packages on the site, and the precise package url should be:
http://packages.flapjack.io/deb/v1/
