### ISSUE TITLE
enumerate all the different runnable parts and ensure that they all have the correct set of requirements loaded

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#757]
Case in point, package build post tests fail with: 

> roberta> Failed build of Flapjack master for centos 6 package (experimental) in 24m 3s, log: http://is.gd/p6fr5J

```
/opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require': cannot load such file -- sandstorm/records/redis_record (LoadError)
from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/lib/flapjack/data/contact.rb:9:in `<top (required)>'
from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/lib/flapjack/cli/import.rb:6:in `<top (required)>'
from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
from /opt/flapjack/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:36:in `require'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:308:in `block in load_commands'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:305:in `each'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:305:in `load_commands'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:38:in `block in commands_from'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:36:in `each'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/gli-2.12.0/lib/gli/app.rb:36:in `commands_from'
from /opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0a1/bin/flapjack:8:in `<top (required)>'
from /opt/flapjack/bin/flapjack:23:in `load'
from /opt/flapjack/bin/flapjack:23:in `<main>'
```

**Comment by ali-graham** [comment]
This is because master currently has zermelo in the Gemfile, not in the gemspec, to avoid having to release a new version of zermelo every time a change is made there. Maybe this should be worked around in packaging until that's changed?

https://github.com/flapjack/flapjack/blob/ac5b160499ac4a6ed21be475b3a0ddc5ac3aa1a4/Gemfile#L5

vs

https://github.com/flapjack/flapjack/blob/ac5b160499ac4a6ed21be475b3a0ddc5ac3aa1a4/flapjack.gemspec#L25

**Comment by jessereynolds** [comment]
@ali how do you propose we work around this in omnibus-flapjack? edit the gemspec before building or something? (shudder)

**Comment by ali-graham** [comment]
Is it possible to pull down the tree and build and install the zermelo gem independently prior to installing flapjack? The gemspec doesn't affect execution as far as I'm aware, just what's required to be installed by 'gem' when installing the described gem.

The other alternative is to pin omnibus-flapjack to certain 'stable' commits in master where we have a zermelo release in the gemspec as expected, and then only update those at appropriate times.

**Comment by jessereynolds** [comment]
> Is it possible to pull down the tree and build and install the zermelo gem independently prior to installing flapjack? The gemspec doesn't affect execution as far as I'm aware, just what's required to be installed by 'gem' when installing the described gem.

Yeah we should be able to add `gem install zermelo` or similar to the flapjack software definition if the flapjack version is not matching "^v1\." or some such. 

> The other alternative is to pin omnibus-flapjack to certain 'stable' commits in master 

I can't think how we would achieve this.

**Comment by ali-graham** [comment]
> Yeah we should be able to add gem install zermelo or similar to the flapjack software definition if the flapjack version is not matching "^v1." or some such. 

The problem with this is that flapjack master is depending on an unreleased version of zermelo, until such time as it makes sense to release that code; if the released gem matched the current flapjack code then the Gemfile pointing to zermelo master could be removed anyway.

We'd need to build the gem locally and then `gem install <file>`, which may not be as easy.

> I can't think how we would achieve this. 

Fail before doing anything if the requested version/commit SHA isn't in a whitelist?

**Comment by jessereynolds** [comment]
maybe we should use bundler.

**Comment by jessereynolds** [comment]
Or we make master always buildable and move zermelo work into a branch that has zermelo installed from Gemfile etc?

**Comment by jessereynolds** [comment]
Or the whitelist. It's a pretty horrible solution but it's simple and gives us a way to proceed with testing package builds of flapjack 2-pre.

**Comment by ali-graham** [comment]
> Or we make master always buildable and move zermelo work into a branch that has zermelo installed from Gemfile etc?

Probably the best solution, as long as we can avoid long-lived branches. I'll clean this up in the next 24 hours.

**Comment by jessereynolds** [comment]
:+1:

**Comment by jessereynolds** [comment]
:tada: thanks, I'll kick off some package builds off master and see how that goes.
