### ISSUE TITLE
Allow separate pagerduty credential per contact (again)

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#774]
This feature exists in 1.x and I believe has been removed in master as per #732 and related flapjack-project mailing list post: https://groups.google.com/forum/#!topic/flapjack-project/wvgGCA2Z7ug

It turns out a few sites are planning to use this feature soon, or already are, so we should get this sorted for 2.0. There's some different implementations proposed by @ali-graham in #732 that need some discussion.

**Comment by bryanyork** [comment]
We'll need this as well for our upcoming project. Do you guys think this will come to the 1.x branch soon, or only in 2.0?

**Comment by jessereynolds** [comment]
It's already in 1.x and always has been. So this issue only affects master (future 2.0).

  Jesse Reynolds
  m: +61 414 669 790

**Comment by ali-graham** [comment]
Just to note; we'll be bolting a userdata hash into the media structure as a stopgap, and particular gateways can expect that this contains the fields it requires. This needs to happen before the release of 2.0. Self-assigning so it's on my list of things TODO.

**Comment by ali-graham** [comment]
Separate hash would have made the validation etc. too hacky, so I've just added the necessary attributes directly to the data model.
