### ISSUE TITLE
Flapjack jabber gateway refers to #{check.state.condition}, which doesn't exist in master

### ISSUE THREAD

**Issue by Hobbsee** [flapjack/flapjack#775]
I can't work out how we're supposed to get the state of a given check - is this a separate lookup?  If so, using what?

**Comment by ali-graham** [comment]
> I can't work out how we're supposed to get the state of a given check -
> is this a separate lookup? If so, using what?

`check.states.last.condition` now, I think. I'll check this, and any 
other errant usage, later tonight.

**Comment by ali-graham** [comment]
`check.states.last.condition` now, I think. I'll check this, and any 
other errant usage, later tonight. (Of course, if `check.states.empty?` then that would fail... and all the usual hedging.)
