### ISSUE TITLE
Support JRuby

### ISSUE THREAD

**Issue by ali-graham** [flapjack/flapjack#780]
I have the initial parts of this in https://github.com/flapjack/flapjack/commit/b28cd6bff290bac2ca9189d14184385dee055fac -- required disabling a couple of incompatible gems. Specs pass, non-CLI features pass (after a single-line fix to zermelo, for something that MRI should have shown up as a bug).

Using `jruby-9.0.0.0pre1`:
* Pact specs fail with stack errors (seems that happens in this branch with MRI as well). `oj` has removed its Java support, so reverting to the `json` library may have caused this.
* The CLI specs tend to fail, but they're fairly hacky anyway; we may need to special-case the steps around the JRuby behaviour.

**Comment by ali-graham** [comment]
I've fixed the stack errors (sets needed `.to_a` before being `.as_json`'d).

In line with #618, I'm removing daemonisation (and the related tests), which may mean this work can't be merged until we have that alternate process supervision support.

The only issue left to fix now is the JSON event feeder, which binds directly to an `oj` handler class.

**Comment by jessereynolds** [comment]
Calling `server status

**Comment by ali-graham** [comment]
Not quite sure what you were trying to say there, but all of the daemonized subcommands only had `start` left, so I moved them up one level, e.g. flapjack is started by `flapjack server` in this branch, not `flapjack server start`. `status` will need to be handled by the external daemonization wrapper, and maybe we should build a CLI conformant with the old one into that.

**Comment by ali-graham** [comment]
`warning: unsupported exec option: close_others` -- possibly GLI trying to do something with input/output that JRuby doesn't support, I haven't looked into it yet.

**Comment by jessereynolds** [comment]
> flapjack is started by `flapjack server` in this branch

Ah I see, yep that works better. Odd that adding 'start' or 'status' after 'server' causes it to hang indefinitely.

**Comment by ali-graham** [comment]
Re the signals/syslog -- I'll look into those, obviously I haven't dug too deep yet. There should be a way to get the JVM to pass through SIGQUIT properly, but I would have thought that JRuby would support the syslog stuff as part of the Ruby core lib.

**Comment by jessereynolds** [comment]
Do we need QUIT? It'd be useful to be able to still trigger the thread dump / stack trace from the JVM.

**Comment by ali-graham** [comment]
Probably not, QUIT it doesn't work on Windows Rubies anyway so it's already a cross-platform fail.

**Comment by ali-graham** [comment]
The hang could be caused by GLI's `exit_now` not cooperating with JRuby, I can look into that as well.

**Comment by jessereynolds** [comment]
The 'processor instances' section of internal statistics shows the uptime of the server process of about 45 years, ie roughly since the unix epoch

![screenshot 2015-02-09 10 27 43](https://cloud.githubusercontent.com/assets/391439/6099386/82c74110-b046-11e4-9c52-c3f8146ce1a9.png)

**Comment by ali-graham** [comment]
On 9/02/2015 10:29 am, Jesse Reynolds wrote:
> The 'processor instances' section of internal statistics shows the
> uptime of the server process of about 45 years, ie roughly since the
> unix epoch

This may not be a JRuby bug, looking at the code; if the executive 
instance id or its boot_time aren't found in Redis, a nil is to_i'd to 0 
and subtracted from the current time.

(There could be other bugs with emitting that data, of course...)

**Comment by ali-graham** [comment]
QUIT removed in fe1f98cb. I couldn't replicate the Syslog error, maybe it's transient?

**Comment by ali-graham** [comment]
Breaking the Flapjack process with Ctrl-C logs "error: 2" before exiting. `flapjack server status` just starts a foregrounded process as normal for me; maybe we should keep the old subcommands around and output error messages, if possible.

**Comment by ali-graham** [comment]
This branch has been merged, we'll address any cleanup in master before the release of 2.0.
