### ISSUE TITLE
API : Wrong Timezone doesn't cause 422 status and makes GET /contacts crash

### ISSUE THREAD

**Issue by nien4521** [flapjack/flapjack#791]
When i create i new contact with a wrong timezone like "kjlhlkjh" or juste an empty timezone, i get a 201 status instead of 422 (if it dosen't do that, then it should) but the worst, is when this contact is created the "GET /contacts/ "  request return : 500 Internal Server Error.

`{"errors":"NoMethodError - undefined method 'name' for nil:NilClass"}`

And i can't anymore see my contacts, to get the contacts again i have to delete the contact with the wrong timezone.

Example of what cause the bug : 

```
POST http://127.0.0.1:3081/contacts
{
    "contacts": [
      {
        "first_name": "Ada",
        "last_name": "Lovelace",
        "email": "ada@example.com",
        "timezone": "",
        "tags": [
          "legend",
          "first computer programmer"
        ]
      }
    ]
  }
```

**Comment by ali-graham** [comment]
The above PR fixes accepting invalid timezone values. Unfortunately, a full validation framework is out of scope for the the maintenance branch at the moment, but the behaviour you describe (returning the correct HTTP status for invalid data) works properly in `master` now and will be in Flapjack v2 when that's released.
