### ISSUE TITLE
Better exception handling in Web and API Webricks

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#794]
Currently in master 794ca24 accessing /self_stats in the web UI returns an internal server error. Nothing about this request is logged in flapjack.log or web_access.log. What should happen when an exception occurs processing a request:
- the request, including response status code, is logged in web_access.log
- the stack trace is logged in flapjack.log along with other details about the request 
- a prettier error page, or json api response, is returned to the http client

**Comment by ali-graham** [comment]
Errors raised within Flapjack itself **should** still be logged properly, but errors between Sinatra/Rack and Webrick are swallowed :disappointed:. This may be a matter of configuring the Webrick logging properly.

**Comment by ali-graham** [comment]
It may also be an error while rendering the ERb template, as I think Sinatra is handling that, and the logging is outside of Flapjack's currently covered areas at that point.

**Comment by jessereynolds** [comment]
If I put a `raise "Screw you!"`into the top of the GET / handler in web.rb then it's handled exactly the same as the TypeError I'm seeing on /self_stats. 

But what i've noticed is that the stack traces DO get logged, but often they're delayed until after a subsequent exception occurs. Sometimes also you get the previous, and the current, stack traces logged at once. So perhaps a buffer is not being flushed as @ali-graham suggested.

**Comment by jessereynolds** [comment]
TypeError from /self_stats is fixed per #795

**Comment by jessereynolds** [comment]
Can we look at switching out Webrick? Maybe for [Puma](http://puma.io/)? Maybe this would help with the exception raising things (among other things).

> WEBrick is the slowest rack server and this shouldn't surprise anyone. As a built in rack server, it does its job admirably and gives a batteries included Ruby experience, but you shouldn’t be using it in production. At all. Ever.

http://www.madebymarket.com/blog/dev/ruby-web-benchmark-report.html

**Comment by ali-graham** [comment]
I'll have a look -- it needs to not assume that it's the only thing running in its process, which too many of these servers do. As long as its server class is individually instantiable and configurable it should be OK.

I'd chosen webrick as it's shipped with the standard library, and it's unlikely to be the slowest part of the request chain anyway.

**Comment by ali-graham** [comment]
Also, the `puma` gem has C/Java extensions, which may complicate building etc.

**Comment by jessereynolds** [comment]
C/Java extensions if an acceptable price to pay for a superior http server.
