### ISSUE TITLE
Get the JSONAPI serving Swagger documentation

### ISSUE THREAD

**Issue by ali-graham** [flapjack/flapjack#799]
Using https://github.com/fotinakis/swagger-blocks ; ideally we'll be able to generate static docs from these once they're done. This will probably be targeting Swagger 1.2 initially, but I'll work on that gem to get it to support Swagger 2.0 as well.

**Comment by jessereynolds** [comment]
@ali-graham this is done, right?

**Comment by ali-graham** [comment]
Mechanically yes, although the documentation itself isn't complete. Closing.
