### ISSUE TITLE
Duration on scheduled maintainence using very large precision

### ISSUE THREAD

**Issue by Hobbsee** [flapjack/flapjack#813]
This is probably a little too much precision!
![screen shot 2015-03-06 at 4 09 23 pm](https://cloud.githubusercontent.com/assets/3038925/6520520/3340289e-c41b-11e4-9b60-b8646236a78a.png)

**Comment by ali-graham** [comment]
The values are stored and retrieved from Redis as floats, and thus the precision is probably a lie at those extremes anyway. Let's round down to ~2 significant figures after the decimal for display.

**Comment by Hobbsee** [comment]
Sure.  This is what that looks like:

![screen shot 2015-03-06 at 5 00 51 pm](https://cloud.githubusercontent.com/assets/3038925/6520908/68b36fe8-c422-11e4-9221-628752efd337.png)

**Comment by Hobbsee** [comment]
The latter option looks better to me:

![screen shot 2015-03-06 at 5 03 59 pm](https://cloud.githubusercontent.com/assets/3038925/6520936/d219c3d8-c422-11e4-8e2a-77ad44143258.png)

**Comment by Hobbsee** [comment]
The attached PR uses the later solution.
