### ISSUE TITLE
Ability for api to look for checks with no contacts

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#818]
@ali-graham said something about virtual association... 

Or maybe store the number of contact of each check...

**Comment by ali-graham** [comment]
Rethinking, might actually store the association data, but keep it read only through the API (as in v2 it's calculated via tag assignments rather than direct linkage). The association will only change when the tags do, which is already the time the rollup cached data is revalidated.

**Comment by ali-graham** [comment]
Accessible in master via `/checks?include=contacts` and then filtering client-side for all checks with an empty contacts array in the returned relationships for the check.
