### ISSUE TITLE
Document how the notification rule data model works in 2.x

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#838]
Pulled out of https://github.com/flapjack/flapjack/issues/676#issuecomment-62686859

**Comment by jessereynolds** [comment]
Rough notes on this:

notification rules have and belong to many tags
checks have and belong to many tags
rule applies to a check if (rule.tags - check.tags) is empty
a contact has_many rules
a contact has_many media
a rule has_many routes
routes match against a single state (string) (TODO should be a has_many to state objects, as in #667, although we won't expose configurability of this until v3 at the earliest)
routes have and belong to many media (from the contact's media only -- a restriction to relax later?), or have no media (equivalent to a blackhole for its matched states)
routes optionally have time restrictions
rollup behaviour is measured against each medium

**Comment by ali-graham** [comment]
http://flapjack.io/docs/2.x/usage/Notification-Routing/ covers this.
