### ISSUE TITLE
Re-instate pagerduty username and password for backwards compatibility in jsonapi

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#847]
So that people's tooling doesn't break, but the data will not be used as the pagerduty gateway now uses the token auth

**Comment by jessereynolds** [comment]
Actually, #831  breaks our commitment to semantic versioning. 

We could prefer token if present, and fail back to username and password? That's maintaining backwards compatibility. Failing that, we should just revert #831.

**Comment by Hobbsee** [comment]
> We could prefer token if present, and fail back to username and password?

If username and password are still working, this is the obvious solution.

**Comment by jessereynolds** [comment]
Fixed
