### ISSUE TITLE
failure delay order of precedence 

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#851]
In 1.3+ this data is only settable in events and if it's not present in an event it gets reverted to the system wide default. 

In 2.x we have the ability to set the delays via the api. 

Lets have the order of precidence as follows:
- use the values in the event if present, otherwise
- use the values in the check (set by the api), otherwise
- use the defaults

**Comment by ali-graham** [comment]
Soon to be merged into master -- done in https://github.com/flapjack/flapjack/tree/832_api_web_gateway at https://github.com/flapjack/flapjack/blob/55bebb01b2a5815fe1e5278ab97f834013692420/lib/flapjack/processor.rb#L238-L246
