### ISSUE TITLE
1.x: pagerduty token auth confusion

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/flapjack#864]
Pull request https://github.com/flapjack/flapjack/pull/831 added an attribute 'token' to the pagerduty credentials of a contact. This would appear to be a duplication in the data model as we already have an attribute 'address' which takes the api token too. 

https://github.com/flapjack/flapjack/pull/853 has since re-instated username and password as a fall back authentication mechanism if token is not present. 

A 1.x release has not yet been cut that includes the above PRs. 

I'd like to clear up the duplication. I propose:
- we remove token
- we use the api token already in the address field to authenticate with the incidents api (as that's what we have always used for creating incidents via pagerduty's events api)
- we ignore any username/password that may be present (but continue to allow these fields to be updated via the api)

As an explanation of why this didn't jump out at me before - I had supposed that 'token' and 'api key' were two different types of authentication credential allowed by pagerduty for different purposes. But when I look at the pagerduty rest api documentation now, I realise 'token' and 'api key' are one and the same. 

We'd need to also remove token in master (v2) and have it use the address field for the incidents api too. 

Thoughts @ali-graham, @alperkokmen, @Hobbsee ?

**Comment by ali-graham** [comment]
On 13/05/15 22:06, Jesse Reynolds wrote:
>
> I'd like to clear up the duplication. I propose:
>
>   * we remove token
>   * we use the api token already in the address field to authenticate
>     with (as that's what we have always used for creating incidents via
>     pagerduty's events api)
>   * we ignore any username/password that may be present (but continue to
>     allow these fields to be updated via the api)

Makes sense, as long as we document it (of course, a v2.x or v3 that 
cleans things up so that each gateway can have its own separate media 
details will be best, but I'm patient...).

**Comment by jessereynolds** [comment]
Oh wow. No, there's still two separate keys Pagerduty use and so we need to keep 'token'. 

The key we're using in 'address' in the 'service_key' as defined by Pagerduty's Events Integration API - https://developer.pagerduty.com/documentation/integration/events

This has always tripped me up. The API docs talk about authentication as being by API key, but this doesn't apply to the Integration API it seems. 

Closing. Nothing to see here. 

![facepalm](https://cloud.githubusercontent.com/assets/391439/7610870/5a8a36ea-f9bf-11e4-8f79-3f4e9da2c744.jpg)
