### ISSUE TITLE
SNS notifications fail when message is > 100 characters

### ISSUE THREAD

**Issue by xcxsxvx** [flapjack/flapjack#865]
SNS notifications fail when the message is more than 100 characters, because flapjack uses the message is as the SNS Subject (as well as the Message), and Amazon only allows 100 characters max in the Subject field.

(see here for Subject restriction: https://docs.aws.amazon.com/sns/latest/APIReference/API_Publish.html)

**Comment by xcxsxvx** [comment]
(see here for Subject restriction: https://docs.aws.amazon.com/sns/latest/APIReference/API_Publish.html)

**Comment by ali-graham** [comment]
Should be fixed in https://github.com/flapjack/flapjack/commit/349b4fc4538d032e307fadc6d7c1cd0b9b0d75a6 , which is in 1.6.0rc2.
