### ISSUE TITLE
How i can set repeat_failure_delay

### ISSUE THREAD

**Issue by Nafania** [flapjack/flapjack#894]
By default it's too often.

I want to set it to my own value. I've tried to set it in config, in processor section like

```
  processor:
    repeat_failure_delay: 3600
```

But it not working and always has default value 60s.

I've tried to send id via json api to httpbrocker like

`curl -X POST -d '{"entity": "test", "check": "test", "type": "service", "state": "ok", "summary": "12345", "repeat_failure_delay": 3600}' http://localhost:3090/state`

But not working too.

How can i set own repeat_failure_delay for checks?

**Comment by jessereynolds** [comment]
@Nafania - you need to include repeat_failure_delay in the event json data, as per the event queue data structure documentation: http://flapjack.io/docs/1.0/development/DATA_STRUCTURES/
