### ISSUE TITLE
Rollup does not prevent alert flood for recoveries

### ISSUE THREAD

**Issue by necula01** [flapjack/flapjack#896]
The current logic for dealing with rollup will allow a flood of Recovery messages in the following scenario:

1. assume rollup = 5, interval = 1 min
1. we get 100 critical events in 1 minute:
   * 5 problem alerts are sent, the last one in rollup mode
   * Redis key drop_rollup_alerts_for_contact is set, with an expiration of 1 min
1. 5 minutes pass
   * The Redis key drop_rollup_alerts_for_contact expires
1. we get 100 ok events in 1 minute
   * each event will keep deleting the drop_rollup_alerts_for_contact
   * each event will result in an alert

The problem is in the following code: 
```ruby
 when alerting_checks >= rollup_threshold
       next ret if contact.drop_rollup_notifications_for_media?(media)
       contact.update_sent_rollup_alert_keys_for_media(media, :delete => ok?)
       rollup_type = 'problem'
```

I think that the `ok?` should be replaced with `false`. 

There are no Cucumber tests to cover that case.

**Comment by ali-graham** [comment]
On 1/10/2015 7:16 am, George Necula wrote:
> The current logic for dealing with rollup will allow a flood of Recovery
> messages in the following scenario:
>

I'll try to look at this today (and write a cucumber test replicating 
it) so we can apply this fix in the maint/1.x line; I think this is 
addressed in master as rollup ceasing is handled differently (in fact 
the notifier logic in general has changed a fair bit). Having a workable 
test that can run in both branches should verify that.

**Comment by necula01** [comment]
I wrote the cucumber test with my pull request.

George.

**Comment by ali-graham** [comment]
On 1/10/2015 10:40 am, George Necula wrote:
> I wrote the cucumber test with my pull request.
>

Ah, thanks, I haven't actually looked at it yet :)

**Comment by necula01** [comment]
I can also show notification.log with flood of recovery messages :-) It is
a real problem.

George.

**Comment by jessereynolds** [comment]
I trust #897 resolves this issue.
