### ISSUE TITLE
Alerting check issue

### ISSUE THREAD

**Issue by phoebuspf** [flapjack/flapjack#917]
hi, in the contact, click on one person, and there are some "alerting checks" there, and one of my services are splitted across different person( they don't have entities in common). How to fix this? Basically this should be blank, and it is blank for my other group of services, but why only this group of entities?

**Comment by jessereynolds** [comment]
Could you send a few screen shots perhaps? Or API dumps? I’m not quite sure what you mean.

**Comment by phoebuspf** [comment]
Thank you for the reply, to be more clear, all people in the contact have same rule, and then alerting checks put different alert to 'some' of the contact un-evenly, say we have problem 1-10, then some one get 3,4,5, some one get 1 and some one get none etc.

**Comment by jessereynolds** [comment]
The idea of a contact is to represent a person that you’re sending alerts to, or an account on an external escalation system such as PagerDuty. 

How have you configured multiple people on the one contact?

**Comment by phoebuspf** [comment]
Ok, so the way it confused me is that why certain fails go to different person, each person is a contact entry, then for example, 100 entries and then 100 point of failure, all people are using same rule of receiving any alerts, then they are getting different alert, PersonA is getting 1,3,5,6, personB is getting 2,4,8... each people have same regex and notification rule.

**Comment by ali-graham** [comment]
There is also visibility scope per person, e.g. https://github.com/flapjack/flapjack-diner/tree/maint/1.x#update_contacts -- a contact's entities act as an overall whitelist for which alerts will be sent, even before the rules are applied.

**Comment by phoebuspf** [comment]
Thank you for the reply, but I have no further configuration, 5 people in the team, 1 is on call, 4 other people share exactly the same rule/notification, but when alert comes it is like assigned to certain people, in the message it also have name in the () pointing to that person only.

**Comment by jessereynolds** [comment]
Do you have multiple processors and/or notifiers running? (Multiple flapjack instances with these roles split?)

**Comment by phoebuspf** [comment]
single machine.

**Comment by jessereynolds** [comment]
Which gateway(s) are you using for notifications?

**Comment by phoebuspf** [comment]
email, slack, twilio

**Comment by jessereynolds** [comment]
Are you able to provide a 'how to reproduce' that is easy for a developer to follow? Ideally include the API requests to add the necessary data (contacts etc) and series of events to play back (and when to play them back).
