### ISSUE TITLE
Cannot suppress spurious recovery events

### ISSUE THREAD

**Issue by necula01** [flapjack/flapjack#920]
Flapjack has the initial_failure_delay parameter for suppressing spurious failure events (a check is in an ok state and then we get a quick sequence of critical and ok events). We need a similar mechanism to suppress spurious recovery events (check is in a critical state and then we get a quick sequence of ok and critical events). 

I propose adding a initial_recovery_delay parameter.

**Comment by jessereynolds** [comment]
This sounds like a good idea to me.

**Comment by ali-graham** [comment]
+1 It makes sense to have these be configurable, as people's use cases will differ.

**Comment by ali-graham** [comment]
There's an initial implementation (against a branch off master, thus targeting v2) in https://github.com/flapjack/flapjack/commit/0407bca1c16ce64057eaf82ccd235d4d734cc5d0 , but I haven't written any tests yet and the old ones are passing only because the recovery delay is set to 0 explicitly (to preserve the old behaviour).

Once complete, this could be backported easily enough if needed.

**Comment by necula01** [comment]
I also have an implementation, on top of maint/1.x, which is the branch we are based off in our production setup. I have a test also. Let me clean it up and publish a pull request. Perhaps you can incorporate my tests in your code.

**Comment by ali-graham** [comment]
Sure, the top-level cucumber features should stay pretty much the same, it's just the steps that change between the versions. My code approach is pretty quick-and-dirty, so I'll check against your implementation too.

**Comment by ali-graham** [comment]
Hmm, my logic's a bit skewed now that I'm testing it, ignore that work for now, I'll have fixes up shortly.

**Comment by ali-graham** [comment]
OK, latest commit in https://github.com/flapjack/flapjack/tree/920_recovery_delay_v2 has something that should work better, first try didn't handle all cases.

**Comment by necula01** [comment]
Here is the code that I have written for this (and deployed in production). It is based on maint/1.x: f62b4637d876

**Comment by ali-graham** [comment]
Looks good from an initial overview, and fairly similar to what I did against master. I should have more time to look at this tomorrow, and hopefully I can then get all tests working on both branches and merge the feature in both in a consistent fashion.

**Comment by ali-graham** [comment]
I didn't get this into the beta, but will do it before the full release of 2.0 and backport the change as well. ('ghost' above is me, account merge didn't go too well :)

**Comment by ali-graham** [comment]
Both branches have support for this now -- https://github.com/flapjack/flapjack/commit/a1b7c212096ad7c9b898ab2ab99e63746f464b81 and https://github.com/flapjack/flapjack/commit/9397028f593ee2c4cba4b7769e583b947b302d5a . flapjack-diner master supports all of the delays as API-addressable check properties as well (as that's something added in v2).
