### ISSUE TITLE
Flapjack alerting on single failure

### ISSUE THREAD

**Issue by CVTJNII** [flapjack/flapjack#925]
I've noticed in my environment that Flapjack will page out an alert after a single failure.  This is annoying as we are monitoring some services that have known bugs and occasionally fail checks as they're restarted by a supervisory process; in this case the service is down and the check correctly fails, but it is a known issue where a page is undesirable.  In this example if a check stays down then I need to be paged.

Looking over the docs I don't see how to tune this behavior.  The 0.9 FAQ states that flapjack asks "How long has a check been failing for?” but I don't see where to set that threshold in the web UI or the API.  Am I missing it?

The one off check section of the 0.9 FAQ implies this time threshold is hardcoded to 30 seconds, is that true?  Does flapjack intend for a very high rate of events?  My checks currently run once a minute, and I do not particularly want to incur the load that will be caused by speeding them up.

**Comment by jessereynolds** [comment]
Hi Tom, 

By default, flapjack needs 2 or more failing events to come in for a check in a row, that span 30 seconds or more, to trigger a notification. 

Each event can pass through custom delays:
- initial failure delay (what you want)
- repeat failure delay

The current failure delay values are exposed in the Web UI page for each check.

See these related PRs:

https://github.com/flapjack/flapjack/pull/849 <https://github.com/flapjack/flapjack/pull/849>
https://github.com/flapjack/flapjack/pull/748 <https://github.com/flapjack/flapjack/pull/748>

See also the Event Queue data structure documentation - look for initial_railure_delay and repeat_failure_delay

Clearly this needs to be better articulated in the documentation! 

Cheers
Jesse

**Comment by CVTJNII** [comment]
Aah, I see.  So if I'm reading these PRs right the defaults are hardcoded in [flapjack.rb](https://github.com/flapjack/flapjack/blob/maint/1.x/lib/flapjack.rb#L7-L9).  However, Flapjack isn't supposed to be managing them.  They are intended to be set by the check data from upstream via the initial_failure_delay and repeat_failure_delay keys in the check data written to Redis.  So for the community Sensu handler those two keys should be added to the [flapjack_event hash](https://github.com/sensu/sensu-community-plugins/blob/master/extensions/handlers/flapjack.rb#L82-L91), correct?

**Comment by jessereynolds** [comment]
Yes, that sounds about right.
