### ISSUE TITLE
Modify the default Notification rule creates a new one

### ISSUE THREAD

**Issue by hanynowsky** [flapjack/flapjack#928]
Hello,
If you create a new contact, a default notification rule gets created with it and if you delete that notification rule, it gets regenerated immediately. Well, that is fine untill now.
If I modify the warning_media or the critical_media, the notification gets updated correctly but if I update anything else, like entities_regex, a new notification rule gets created.
I thought this was implemented on pupose but when I tested, i was still receiving alerts for entities that did not match the entities_regex, which means the newly created notification rule is always overriden by the default one.

So what I see now is that the default open notification rule is the active one regadless of whatever notification rules you create for a given contact,(they will be non effective.) 

Am I doing something wrong?
FlapJack 1.6

**Comment by jessereynolds** [comment]
When you make the notification rule apply to only some entities then Flapjack creates a new catch-all rule. You'd then need to disable the media on the new catch-all rule if you don't want notifications for everything not more specifically matched by other notification rules.

**Comment by hanynowsky** [comment]
Ok Got it. I managed to script a ruby caller to do that on the fly.

**Comment by jessereynolds** [comment]
Nice one @hanynowsky
