### ISSUE TITLE
Changes to transport.go broke build.sh

### ISSUE THREAD

**Issue by Buzer** [flapjack/flapjack#930]
Currently build.sh (and due to that omnibus-flapjack) is not working due to changes to ```Transport.Send()```'s signature
```shell
root@efb43697cbaf:/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0# PATH=$PATH:/usr/local/go/bin bash -x ./build.sh 
+ set -e
++ pwd
+ export GOPATH=/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0:/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0:
+ GOPATH=/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0:/opt/flapjack/embedded/lib/ruby/gems/2.1.0/gems/flapjack-2.0.0:
+ go get github.com/garyburd/redigo/redis
+ go get github.com/go-martini/martini
+ go get gopkg.in/alecthomas/kingpin.v2
+ go get github.com/oguzbilgic/pandik
# github.com/oguzbilgic/pandik
src/github.com/oguzbilgic/pandik/notifier_flapjack.go:40: not enough arguments in call to transport.Send
```

I think there are few different ways this could be fixed:

1) Backport change to 1.x and make the change in oguzbilgic/pandik

2) Make a new method that uses the new signature. Make PR to to pandik to use the new method. Deprecate Transport.Send and make it call the new method with v1 parameters for backwards-compatibility. You may need to remove pandik from 2.x until then or use forked version.

**Comment by ali-graham** [comment]
`travis.yml` should probably run that script as well, to catch any problems in the future.

**Comment by ali-graham** [comment]
Thanks for this, I think the fact that I already had the old `go get`-ted packages around stopped me from seeing any breakages...
