### ISSUE TITLE
custom email templates are ignored

### ISSUE THREAD

**Issue by zoran** [flapjack/flapjack#933]
- enable custom email templates in **flapjack_config.toml.erb**:
```
[gateways.email.templates]
  rollup_subject_text = "/etc/flapjack/templates/email/rollup_subject.text.erb"
  alert_subject_text = "/etc/flapjack/templates/email/alert_subject.text.erb"
  rollup_text = "/etc/flapjack/templates/email/rollup.text.erb"
  alert_text = "/etc/flapjack/templates/email/alert.text.erb"
  rollup_html = "/etc/flapjack/templates/email/rollup.html.erb"
  alert_html = "/etc/flapjack/templates/email/alert.html.erb"
```

- change something in the email (html) template:
```
echo "<p>this will be ignored</p>" >> /etc/flapjack/templates/email/alert.html.erb
````

- restart flapjack and simulate a fail:
```
flapjack simulate fail --tags test_fail --interval 10 --check test_check
```

You will not see 

> this will be ignored

 in the notification email.

**Comment by ali-graham** [comment]
This might depend on the packaging, and which config file Flapjack is looking at (default is `/etc/flapjack/flapjack_config.toml`, can be changed from the CLI) -- and also whether the text or HTML part of the mail is being viewed. Can you add the full output of the generated mail including both content types (clear any sensitive headers if needed)?

**Comment by jessereynolds** [comment]
Please re-open if you decide to add more info @zoran
