### ISSUE TITLE
Flapjack Diner regression

### ISSUE THREAD

**Issue by hanynowsky** [flapjack/flapjack#940]
<senshuha> hello guys
 I have a problem with FlapJack Diner
 I wrote a script months ago that used to work perfectly
 I wanted to use now and I got this error :
 # /opt/sensu/embedded/bin/ruby flapjack-create-contact.rb 
 flapjack-create-contact.rb:40:in `<main>': undefined method `entities' for Flapjack::Diner:Module (NoMethodError)
 the method entities disappeard or what ?
 jesser, any idea why entities method was removed
 ?;
 Sounds like everything related to entities was removed; Oh gosh no!
<-- Naresh has quit (Quit: Connection closed for inactivity)
<senshuha> So what is in here is no more valid! : http://flapjack.io/docs/1.0/jsonapi/?ruby#get-entities

**Comment by tom-tuddenham-bulletproof** [comment]
Sounds like you've upgraded to Flapjack 2.0? Or at least have a version of Flapjack Diner that's meant for Flapjack 2.0.

Earlier versions of Flapjack handle entities differently - they are explicitly registered, whereas version 2.0 records entities as they appear in the event stream. From my understanding, this is to support dynamic services (i.e. entities appearing on an ad hoc basis).

Short term solution might be to roll back Flapjack Diner to an earlier versior (in the 1.x series), but that will depend on what version of Flapjack you are actually running. Longer term will be to drop the entities references from your script. You don't actually need to explicitly create them - they will be created on first event that references them (or so I understand).

**Comment by jessereynolds** [comment]
Like Tom says, try rolling back to a 1.x version of flapjack-diner. 

Entities have totally gone from Flapjack 2. Entities have been replaced by a more general grouping mechanism employing tagging.
