### ISSUE TITLE
Flapjack created list "events" on first try, now creates many Zsets

### ISSUE THREAD

**Issue by jcosentino** [flapjack/flapjack#954]
I am using flapjack 1.6 on Ubuntu 16.04
I ran this from the flapjack tutorial:
`flapjack simulate fail \
  --entity restaurant1 \
  --check bacon \
  --interval 1 \
  --time 0.1

flapjack simulate ok \
  --entity restaurant1 \
  --check eggs \
  --interval 1 \
  --time 0.1

flapjack simulate fail_and_recover \
  --entity restaurant2 \
  --check pancakes \
  --interval 1 \
  --time 0.1`

All of the resulting data was placed into a list called "events", which was dilmeted quite nicely.
However upon restarting my machine, events was gone from my Redis database.
I ran the code from above ^ again, and now have multiple Zsets instead of one list.
This is shown in the attachment.

Why did this happen?
<img width="960" alt="virtualbox_ubuntu 16 04_30_03_2017_09_43_54" src="https://cloud.githubusercontent.com/assets/1408654/24507741/4d6d7bf6-152f-11e7-8b99-d0e0b0d1ab0c.png">

**Comment by jessereynolds** [comment]
As flapjack processes incoming events it removes them from the list, and then updates various other data structures in redis such as the ones you see. This is how flapjack processes events. It then uses these data structures to determine whether notifications should be generated.
